### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Wasabi72** [baracudaz/netatmo-lametric-proxy#1]

**Comment by baracudaz** [comment]
Hi wasabi,

Thanks for your interest. I have added a couple of extra comments to README and a few screenshots to   clarify the setup process.
1. Any numbers would do. The script will push the new values anyway.
2. Make sure to set the communication type to Push. The script will push the values.

HTH

**Comment by Wasabi72** [comment]
Hi baracudaz,

Big thanks for the Help. :-)

But...the next Problem :-(
The "_updateLaMetric.py_" generate ever an error -> "**Internal Server Error**" 
The LaMetric- and Netatmo-Authentication-Values is in the File.
The Chmod is on 755
But, the Error comes ever and ever again.

Python works on my web space without any problems. (I tested it with a small Pythonscript)
But unfortunately the "_updateLaMetric.py_" will not working.
I have no idea what is wrong.

Unfortunately does not appear in Python where the error is.
the errors are displayed precisely in PHP.
Can you do that in Python also?
Or programmed identically in php (if it is feasible

**Comment by baracudaz** [comment]
Do you have a full error message? My guess is problem with the credentials.

BTW, if you are interested in PHP take a look at [this blog](http://fabburst.fr/index.php/2015/12/27/netatmo-et-lametric/)

**Comment by Wasabi72** [comment]
Hi baracudaz,

the Full Error Message is:

#### Internal Server Error

**The server encountered an internal error or misconfiguration and was unable to complete your request.**

**Please contact the server administrator and inform them of the time the error occurred, and anything you might have done that may have caused the error.**

**More information about this error may be available in the server error lo**

**Comment by baracudaz** [comment]
Huh? Did you get this message while running the python script itself? I don't see any python related output or line number with the error, etc.

**Comment by Wasabi72** [comment]
Hi,
the my (Your) script running on my Webspace/Website an call this error message.

I will now call the script via shell and see if there an error message is generated.

**Comment by Wasabi72** [comment]
OK....here the Error via Putty:

**ssh-w00xxxx@ddxxxx:/www/htdocs/w00xxxx/wetter$ python updateLaMetric.py
Detected outdoor module: 02:00:00:13:xx:xx 'Out'
Detected outdoor module: 05:00:00:01:xx:xx 'Rain'
Detected station module: 70:ee:50:13:xx:xx 'In'
Traceback (most recent call last):
  File "updateLaMetric.py", line 63, in <module>
    hist_temp = [v[0] for v in measure['body'][0]['value']]
IndexError: list index out of range**

You see, I still have the rain sensor in addition to the normal outdoor unit. Its that the "Error" ?

How can I add different modules in the script?
With the MAC address?

**Comment by baracudaz** [comment]
Perfect! Yep, the script is meant to be run from command line or better via cron. It does not serve any web page.

Back to the issue. You are absolutely right regarding the extra modules. I don't have any just a station (Indoor) with one Outdoor module. 

Anyway I have updated the script to implement better auto-detection. You are welcome to try again and report back.

**Comment by Wasabi72** [comment]
Hi,
thanks for Help.

Here the next Putty-Output:

ssh-w00xxxx@ddxxxx:/www/htdocs/w00xxxx/wetter$ python updateLaMetric.py
Detected outdoor module: 02:00:00:13:xx:xx 'Out' - Temperature, Humidity
Detected outdoor module: 05:00:00:01:xx:xx 'Rain' - Rain
Detected station module: 70:ee:50:13:xx:xx 'In' - Temperature, CO2, Humidity, Noise, Pressure
{'trend': 'stable', 'pressure': '1014.5mb', 'temperature': '11\xc2\xb0C', 'humidity': '80%'}
The server couldn't fulfill the request.
('Error code: ', 404)
{"error":{"message":"Not Found","trace":["Application not found"]}
